#!/usr/bin/env python
""" Script to run kinematic replay. """

from NeuroMechFly.experiments.kinematic_replay import \
    kinematic_replay_no_support
from farms_container import Container
import os
import argparse
from pathlib import Path
import pkgutil
import glob
from datetime import datetime

neuromechfly_path = Path(pkgutil.get_loader(
    "NeuroMechFly").get_filename()).parents[1]

if __name__ == "__main__":
    """ Main. """
    parser = argparse.ArgumentParser()
    parser.add_argument('-b', '--behavior', default='walking')
    parser.add_argument('--record', dest='record', action='store_true')
    parser.add_argument(
        '-p',
        '--perturbation',
        default=False,
        action='store_true')
    args = parser.parse_args()

    run_time = 6.0
    time_step = 0.001
    behavior = args.behavior.lower()

    # Setting up the collision and ground sensors
    side = ['L', 'R']
    pos = ['F', 'M', 'H']
    leg_segments = ['Tibia'] + ['Tarsus' + str(i) for i in range(1, 6)]
    left_front_leg = ['LF' + name for name in leg_segments]
    right_front_leg = ['RF' + name for name in leg_segments]
    body_segments = [s + b for s in side for b in ['Eye', 'Antenna']]

    self_collision = []
    for link0 in left_front_leg:
        for link1 in right_front_leg:
            self_collision.append([link0, link1])

    for link0 in left_front_leg + right_front_leg:
        for link1 in body_segments:
            if link0[0] == link1[0]:
                self_collision.append([link0, link1])

    ground_contact = [
        s +
        p +
        name for s in side for p in pos for name in leg_segments if name != 'Tibia']

    # Setting up the paths for the SDF and POSE files
    model_path = os.path.join(
        neuromechfly_path,
        'data/design/sdf/neuromechfly_kinematic_replay_no_support.sdf')
    pose_path = os.path.join(
        neuromechfly_path,
        'data/config/pose/pose_tripod.yaml')
    # Simulation options
    sim_options = {
        "headless": False,
        "model": model_path,
        "pose": pose_path,
        "model_offset": [0, 0., 0.5e-3],
        "run_time": run_time,
        "time_step": time_step,
        "base_link": 'Thorax',
        "ground_contacts": ground_contact,
        "self_collisions": self_collision,
        "record": False,  # Set True to record the simulation
        'camera_distance': 7.0,
        'track': False,  # Set True to track the animal automatically
        'moviename': './kinematic_replay_ground.mp4',
        'moviespeed': 0.2,  # Speed of the recorded movie
        'slow_down': False,
        'sleep_time': 0.1,
        'rot_cam': False,
        'behavior': behavior,  # Set true to rotate the camera automatically
        'ground': 'floor',
        'num_substep': 5
    }

    # Paths of the position and velocity data
    data_path = os.path.join(
        neuromechfly_path,
        f'data/joint_tracking/{behavior}/df3d')
    angles_path = glob.glob(data_path + '/joint_angles*.pkl')[0]
    velocity_path = glob.glob(data_path + '/joint_velocities*.pkl')[0]
    # Initialize the container
    container = Container(run_time / time_step)
    # Initialize the simulation
    animal = kinematic_replay_no_support.DrosophilaSimulation(
        container,
        sim_options,
        kp=0.4, kv=0.9,
        angles_path=angles_path,
        velocity_path=velocity_path,
        add_perturbation=args.perturbation,
    )
    # Run the simulation
    animal.run(optimization=False)
    # Dump the results based on the date
    animal.container.dump(
        dump_path=os.path.join(
            neuromechfly_path,
            'scripts/kinematic_replay/kinematic_replay_ground_{}_{}'.format(
                behavior,
                datetime.now().strftime('%y%m%d_%H%M')
            )
        ),
        overwrite=False
    )
