joints:
  joint_LFCoxa: 19
  joint_LFFemur: -110
  joint_LFTibia: 79
  joint_LFTarsus1: -39 

  joint_LMCoxa: -5
  joint_LMCoxa_yaw: 7.45
  joint_LMCoxa_roll: -110
  joint_LMFemur: -107
  joint_LMTibia: 130
  joint_LMTarsus1: -54 

  joint_LHCoxa: 6.2
  joint_LHCoxa_yaw: 3.45
  joint_LHCoxa_roll: 143
  joint_LHFemur: -109
  joint_LHTibia: 109
  joint_LHTarsus1: -45
  
  joint_RFCoxa: 29 
  joint_RFFemur: -122 
  joint_RFTibia: 105
  joint_RFTarsus1: -52

  joint_RMCoxa: -8.75
  joint_RMCoxa_yaw: -0.22
  joint_RMCoxa_roll: -113
  joint_RMFemur: -129
  joint_RMTibia: 143
  joint_RMTarsus1: -54

  joint_RHCoxa: 10
  joint_RHCoxa_yaw: 0.74
  joint_RHCoxa_roll: 150
  joint_RHFemur: -117
  joint_RHTibia: 125
  joint_RHTarsus1: -51