joints:

  joint_prismatic_support_1: 0
  joint_prismatic_support_2: 0
  joint_Thorax: 0
  joint_A1A2: 0
  joint_A3: -15
  joint_A4: -15
  joint_A5: -15
  joint_A6: -15
  joint_Head_roll: 0
  joint_Head_yaw: 0
  joint_Head: 10
  joint_LAntenna: 33
  joint_LEye: 0
  joint_RAntenna: -33 
  joint_REye: 0
  joint_Rostrum: 90
  joint_Haustellum: -60
  joint_LFCoxa_roll: 10
  joint_LFCoxa_yaw: 0
  joint_LFCoxa: 53  
  joint_LFFemur: -154
  joint_LFFemur_roll: 0
  joint_LFTibia: 130
  joint_LFTarsus1: -43
  joint_LFTarsus2: 0
  joint_LFTarsus3: 0
  joint_LFTarsus4: 0
  joint_LFTarsus5: 0
  joint_LHCoxa: 13
  joint_LHCoxa_yaw: 0.6
  joint_LHCoxa_roll: 139
  joint_LHFemur: -69
  joint_LHFemur_roll: 0
  joint_LHTibia: 58
  joint_LHTarsus1: -45
  joint_LHTarsus2: 0
  joint_LHTarsus3: 0
  joint_LHTarsus4: 0
  joint_LHTarsus5: 0
  joint_LHaltere_roll: 0
  joint_LHaltere_yaw: 0
  joint_LHaltere: 0
  joint_LMCoxa: -2
  joint_LMCoxa_yaw: 4
  joint_LMCoxa_roll: 82
  joint_LMFemur: -132
  joint_LMFemur_roll: 0
  joint_LMTibia: 149
  joint_LMTarsus1: -52
  joint_LMTarsus2: 0
  joint_LMTarsus3: 0
  joint_LMTarsus4: 0
  joint_LMTarsus5: 0
  joint_LWing_roll: 90
  joint_LWing_yaw: -17
  joint_LWing: 0
  joint_RFCoxa_roll: -10
  joint_RFCoxa_yaw: 0
  joint_RFCoxa: -15
  joint_RFFemur: -54
  joint_RFFemur_roll: 0
  joint_RFTibia: 37
  joint_RFTarsus1: -49
  joint_RFTarsus2: 0
  joint_RFTarsus3: 0
  joint_RFTarsus4: 0
  joint_RFTarsus5: 0
  joint_RHCoxa: 11.4
  joint_RHCoxa_yaw: 6.2
  joint_RHCoxa_roll: -144
  joint_RHFemur: -131
  joint_RHFemur_roll: 0
  joint_RHTibia: 165
  joint_RHTarsus1: -50
  joint_RHTarsus2: 0
  joint_RHTarsus3: 0
  joint_RHTarsus4: 0
  joint_RHTarsus5: 0
  joint_RHaltere_roll: 0
  joint_RHaltere_yaw: 0
  joint_RHaltere: 0
  joint_RMCoxa: -4.5
  joint_RMCoxa_yaw: -0.5
  joint_RMCoxa_roll: -125
  joint_RMFemur: -96
  joint_RMFemur_roll: 0
  joint_RMTibia: 95  
  joint_RMTarsus1: -56
  joint_RMTarsus2: 0
  joint_RMTarsus3: 0
  joint_RMTarsus4: 0
  joint_RMTarsus5: 0
  joint_RWing_roll: -90
  joint_RWing_yaw: 17
  joint_RWing: 0