name: "Github pages CI/CD"
on:
  push:
    branches:
      - master # TODO: Change to main once branches are renamed
      - setup-github-pages
jobs:
  pages:
    name: Build and deploy github pages
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
      - name: Start
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Install prerequisities
        run: |
          set -x
          apt-get update
        shell: bash
      - name: Check out repository code
        uses: actions/checkout@v2
        run: |
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Run build script for Sphinx pages
        run: "docs/buildsite.sh"
        shell: bash
